name: Lint

on: push

jobs:
  run-linter:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
